### PR TITLE
Fix #275. Add srcbuf-mode to allow cleaning up shortcuts at quit.

### LINKED ISSUE #65: Several issues with mixed up keybindings
There are several issues with mixed up keybindings in realgud. I have a `(global-set-key [f5] 'realgud:cmd-step)` in my init.el. This is resetted to something horrible, although I set `realgud-populate-common-fn-keys-function` to `nil` in my init.el. 

This will be addressed partially in a forthcomming pull request. 

After my patch, this issue is not completely gone, however. `realgud:cmd-step` is still resetted to f11  sometimes, although I can't find where this is done. I will further investigate possibly.

Another question would be, why `realgud-populate-common-keys` is called nearly after _every_ action in realgud.
Best regards,
Kilian.

### LINKED ISSUE #275: realgud clobbers major modes' keymaps, and does not restore them on quit
After a debugging session, I noticed that some keys stop working, even after realgud is fully exited (using `realgud:cmd-quit`).

E.g., see this with `describe-key`:

```
<M-down> runs the command realgud-track-hist-newer (found in
d-mode-map), which is an interactive compiled Lisp function in
‘realgud/common/track.el’.
```

Obviously `realgud-track-hist-newer` has no business being in `d-mode-map`.

The biggest annoyance is that this corruption is "global" - recreating the buffer (by closing and re-visiting the file) does not fix it. Only restarting Emacs helps.

realgud 20200722.1113 with GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw scroll bars) of 2019-09-07.

### PR DESCRIPTION
**Pull request by 813gan**
Close #275. Close #65.

@rocky Please take a look if i'm not breaking something...

### CODE REVIEW

**Comment by 813gan** [comment]
It turns out i'm bad at writing automatic tests...
@rocky do you have idea what should be placed in asserts there?/
Is this skeleton even usable?

```lisp
(require 'test-simple)

(test-simple-start)

(note "realgud-keymap-cleanup")

(setq proc-srcbuf (generate-new-buffer "*procbuf-test*"))
(setq temp-srcbuf (generate-new-buffer "*srcbuf-test*"))
(with-current-buffer temp-srcbuf
  (python-mode) )
(setq debugger-name "pdb")
(load-file "../realgud/debugger/pdb/pdb.el")
(realgud-srcbuf-init-or-update temp-srcbuf proc-srcbuf)

(with-current-buffer temp-srcbuf
  (assert-t       ) )

(realgud:terminate-srcbuf temp-srcbuf)

(with-current-buffer temp-srcbuf
  (assert-nil     ) )

(end-tests)
```

**Comment by rocky** [comment]
Just as writing code should be an expression of how to solve something, writing a test should be an expression of what was wrong that doesn't happen again. 

So, forgetting about the testing framework(and yes the above looks correct), decscribe a situation using specific examples where the current code does something bad. 

Then just wrote some code that exhibits this. And the figure out how you'd detect that somehting is wrong. Here, I imagine that  is he function `(keybinding <key>)` and checking the value returned will tell you. 

If you do this part of it, I think fitting it into the test framework part will be pretty easy. I use that particular test-simple thing because well, it really is simple. If you can write code to show what's bad then adding a few tests or "asserts" is pretty simple.

**Comment by 813gan** [comment]
OK. I have no idea why it was that hard to reproduce it in non-interactive session.

**Comment by CyberShadow** [comment]
Thank you!

**Pull request merged**
