### PR TITLE
add eval at point and bind it to E in shortkey mode

### PR DESCRIPTION
**Pull request by jodonnell**
a nice little shortcut in shortkey mode, when you hit E it will immediately eval whats under the point

### CODE REVIEW

**Comment by rocky** [comment]
Good idea. Looks good. Thanks.

**Comment by rocky** [comment]
It just occurred to me that it might be slick to mark the part of the source buffer that is getting eval'd.

**Comment by jodonnell** [comment]
Hmmm, not sure I understand, do you mean move the mark to one side of the thing-at-point and then the point to the other side so the thing-at-point is in the users region?  I thought it was considered bad form to have a command monkey with the users point or mark.

**Comment by rocky** [comment]
Ok. But there must be more to it than "bad form to have a command monkey with the users point or mark." 

There are commands that explicitly do that. The intent here would be to highlight what has been evaluated, and perhaps there could be a command that shows by marking what _would_ be highlighted if it were to be eval'd.

Let me back up a little though. In the little that I've used this, I find whatever it is not picking up the text that I would have expected. Part of the problem no doubt is in the debuggers. For POSIX shell things, (bash zsh, ksh), and possibly even gdb there probably needs to be a separate command for "print" versus "eval". 

And if there is no mark/region set, I don't see the harm in having it mark the region it decided to evaluate and thus show what's going on easier and get me one step closer should I decide to alter it.

Recall that these buffers are read only or for mostly display purpose. So I imagine there is very little marking going on anyway. 

That said, by far, my sense of design isn't very good. So I defer to others judgement especially on such things. 

By the way, Stefan has recently [made a change in realgud on elpa](http://git.savannah.gnu.org/cgit/emacs/elpa.git/commit/?id=1aad21336c817c8cf3e04fe65899cecc969f53bb). I have mirrored those changes.

**Comment by jodonnell** [comment]
Hmm yes I think this command as is, is problematic.

I think if the point was on top of the p in print('hi') would expect it to output 'hi' but since I am using thing-at-point 'symbol its just going to eval print which would return a function.  As the implementor I expected this to only really work when you are on top of a variable you want evalled but I don't think thats ideal at all.

If this did something more like the concept of a sexp I think that would match peoples expectations a lot better.  I tried using (sexp-at-point) but I think that might only work in elisp mode.

Maybe your solution of also making the thing-at-point the region would be good enough so that users understand whats happening.

Another idea is when you hit E it can load the same eval command read prompt you get when you hit e, except now the thing at point would be pre-populated.  Hmm, I think I like that, what do you think?

Finally, another idea is we remove this for now if its just not well thought out enough.

**Comment by rocky** [comment]
Sorry for the delay - I wanted to check things out. Yes the command has problems. 

I would have hoped that each programming mode would do something reasonable for "mark word", but that is not the case. There are various xxx-at-point functions but even if there were something to tie all those together, they don't do what one probably wants. 

I like the idea of another command like E prompting with a reasonable suggestion if that can be done, _and_ marking the suggestion at the same time. Then if the user modifies that, the mark would be modified accordingly if possible. (If not the mark disappears). That allows one to start with something and modified. But this is all getting complex. 

I'm also cool with removing for now, since this idea doesn't look like it will pan out right now. 

Your choice. I'll be refreshing ELPA once I hear from you.

**Pull request merged**
