### PR TITLE
Locals window v2.1

### LINKED ISSUE #191: locals
Is there a way to have a window showing locals?

If not are there any pointers on how I might implement it for python usine trepan or ipdb?

Thanks!

### PR DESCRIPTION
**Pull request by 813gan**
As we discussed, I'm opening pull request.

I'm setting it to draft as i want to introduce frame identification.

Once merged, this pr closes #191

### CODE REVIEW

**Comment by 813gan** [comment]
Thanks, i had no idea whats going on. I rebased and force-pushed branch.

**Comment by 813gan** [comment]
OK. i realized that i have no idea how to correctly identify frames, at least not for pdb.

**Comment by rocky** [comment]
> OK. i realized that i have no idea how to correctly identify frames, .. 

What exactly do you mean by this? 

Is this the same thing as a gdb (or trepan3k, trepan2) frame command?

**Comment by 813gan** [comment]
I'm not sure how to call it correctly; scopes? In most languages it's about functions/methods.

**Comment by 813gan** [comment]
I don't know what are your preferences when it comes to PRs. If many small Pull requests, then I bet I'm done for now.

**Comment by rocky** [comment]
> I don't know what are your preferences when it comes to PRs.

We get so few PRs that  there isn't a preference. Go with whatever you think best or is easiest. If it becomes a problem, we'll adjust down the line. 

Also, with this successful PR, I'll add an invite to become a contributor.

**Comment by 813gan** [comment]
@rocky Thanks. See you in next PRs ;)

**Pull request merged**
