### PR TITLE
common/helper: require cl

### PR DESCRIPTION
**Pull request by dunn**
Otherwise `make check` can lead to this error: https://gist.github.com/dunn/ee1080dd3b32aaf8594d3c8368da7bde

### CODE REVIEW

**Comment by rocky** [comment]
Thanks.

**Comment by dunn** [comment]
Did you mean to close instead of merging?

**Comment by rocky** [comment]
Sorry. Yes, meant to merge. Thanks.

**Comment by dunn** [comment]
No problem, thank you for the quick turnaround!

**Pull request merged**
