### PR TITLE
Filter lists

### PR DESCRIPTION
**Pull request by rocky**
This is a largish, but I think needed change. 

The basic idea is to allow extend the notion of black-listed files when they aren't found. In gdb, assembly with or without source would fit here. In Ruby, there is often a compiled-in bootstrap file. V8 may have such files as well. 

The blacklist regexps are per debug session but they are seeded by the specific debugger. For example in Python it is known that `<string>`, doesn't refer to real file. Likewise for Perl and `<eval>`. 

Another change is to is in the  table which was used to remap file names seen in a session with those in a filesystem. Before there was just one hash table for all debug sessions. As with the blacklist regexps, it is now set per debug session. It is also now an association list where it had been a hash table. 

Obviously it would be nice to allow marking transformations to span across different debug sessions, or allow some sort of configuration file to supplement seed the lists, but as with many things, there is way more work needed than time I want to spend on. 

And this already is a bit large. I put out a stable release on MELPA and ELPA previously. There haven't been complaints on either. So hopefully that can be used to fall back on.

### CODE REVIEW

**Comment by rocky** [comment]
Ok. No comments, so we'll just take the plunge....

**Comment by jodonnell** [comment]
I don't quite understand, does this have to do with eval constructs in languages?

Or more generally the idea that you could step into some code that doesn't actually exist?

If the latter, whats the advantage of blacklisting files rather than generally handling the situation that you cannot find an associated file?

**Comment by rocky** [comment]
The relation is a bit indirect. The debugger for languages that allow you to create code at run time, generally also let you step inside and debug that code. Each debugger has a way to describe location in code created at runtime and that is not stored as a file in a filesystem.. I think it lame, but location in many languages like Perl, Ruby and Python consists of a field called a "filename". When code is created at runtime that is not associated with a file in a filesystem, the name is bogus or I think they would say it is a "pseudo file". In Perl, Python and Ruby these have names like "<eval>", or "<string>". 

Some of my debuggers are a bit more careful here in that, when I can I'll extract and create _create_ a temporary file in the filesystem that contains source-code contents of that is getting run, and then I'll jigger the location reported in the debugger to point to that. But this is the exception rather than the rule.

For those languages that can create these "pseudo files", realgud's debugger description has regexp field to the kinds of file names that are "pseudo files". If a file name matches that realgud does not try to find these in the filesystem. (Note though that this is sometimes a function of the programming language implementation. So all debuggers that use CPython can draw on the same description of what a CPython pseudo file looks like). 

But there are other situation where one wants to tell realgud not to try to look for file locations in a filesystem. Even though the code wasn't created at runtime, it could be that you simply don't have the source code around. Or might simply be that you are not be interested in looking at certain kinds of source code like assembly language files when run under gdb. 

So the notion of how to tell realgud not to bother to look for a filename in a filesystem has been expanded. Whereas it had been  a been a single regular expression based on the debugger, it is now a list of regexps that gets seeded by the a particular debugger. (In the future there could be other ways to seed that list of regexps). And that list is specific to the debugger session, although probably there should be ways to indicate it be global to all debugger sessions of a certain kind.

When realgud can't find a file for a location it sees, it now prompts you if you to add to the blacklist of regular expressions. I probably have more work to turn the prompted filename string into a properly anchored regexp. But I've deferred that for later.

**Comment by jodonnell** [comment]
Yes this seems like a reasonable change.

**Pull request merged**
