### PR TITLE
Add flake8 pattern

### PR DESCRIPTION
**Pull request by rocky**

### CODE REVIEW

**Comment by cpitclaudel** [comment]
I'm a bit confused; what did this PR do?

**Comment by rocky** [comment]
I wanted to add a dinky pattern for parsing python flake8 messages. In the process I think I messed up badly because somehow I had a messed up git repo on my laptop. I think I had realgud checked out one level too high. 

So the intent was to revert the messed up comment that has lots of changed files. And then apply the flake8 change which is about 6 files ( python debugger init files and python.el and a test for that).

Please double check to see that things still aren't horribly broken.

**Comment by cpitclaudel** [comment]
Oh, I see :)  I wonder if this would be a good candidate for a force-push, just forgetting this part of the history.

**Comment by rocky** [comment]
If things are still funky and/or you want to clean up the mess I made please go ahead.

**Pull request merged**
