### PR TITLE
fix issue: failed to load file realgud/common/helper.

### PR DESCRIPTION
**Pull request by yangyingchao**
Not sure if this is correct, but for me, realgud failed to load without this patch.

Thanks.

### CODE REVIEW

**Review by rocky — COMMENTED** [review]
Thanks for the PR.  Some questions: 

* Do you have the error message that was produced that this eliminates? 
* How/why  does this work? 

@813gan your thoughs?

**Comment by yangyingchao** [comment]
1. In file `locals-mode.el`, if i move cursor to line 20,
```elisp
(require-relative "helper" "realgud-")
```
 then stroke `C-x C-e`, error occurs:
```
Debugger entered--Lisp error: (error "Loading file /home/arthas/.emacs.d/elpa/realgud-20200919.2302/realgud/common/helper.el failed to provide feature ‘helper’")
  require(helper "/home/arthas/.emacs.d/elpa/realgud-20200919.2302/r...")
  (let ((require-string-name (concat opt-prefix (file-name-sans-extension (file-name-nondirectory relative-file))))) (require (intern require-string-name) (relative-expand-file-name relative-file opt-file)))
  require-relative("helper" "realgud-")
  elisp--eval-last-sexp(nil)
```

2. Look into the definition of `require-relative`:

```elisp
(defun require-relative (relative-file &optional opt-file opt-prefix)
  "Run `require' on an Emacs Lisp file relative to the Emacs Lisp code
that is in the process of being loaded or eval'd.  The symbol used in require
is the base file name (without directory or file extension) treated as a
symbol.

WARNING: it is best to to run this function before any
buffer-setting or buffer changing operations."
  (let ((require-string-name
         (concat opt-prefix (file-name-sans-extension
                             (file-name-nondirectory relative-file)))))
    (require (intern require-string-name)
             (relative-expand-file-name relative-file opt-file))))
```

In original `locals-mode.el`, when `require-relative` is called, argument `opt-file` was bind to `realgud-`, `opt-prefix` is bind to `nil`,  then, `require-string-name` evaluates into `helper`. I guess it should be `realgud-helper`, but I'm not sure...

Maybe there is something wrong with my configuration, but everything worked fine before upgrading to`realgud-20200919.2302`...

**Comment by rocky** [comment]
Thanks! Everything you write makes perfect sense. 

> Maybe there is something wrong with my configuration, but everything worked fine before upgrading torealgud-20200919.2302...

I made the last change. And I did that because the tests were failing. 

Now that you explain things, I believe you are correct that there should be a `nil` argument passed in.

**Comment by yangyingchao** [comment]
Sorry, just found next line needs to be modified too:
```
(require-relative "buffer/locals" nil "realgud-buffer-")
```

BTW, no offense, but does it works for you without these modifications?

**Comment by rocky** [comment]
Ok. Please put in another PR. 

> BTW, no offense, but does it works for you without these modifications?

Yes. I use it all the time.

**Comment by yangyingchao** [comment]
> Ok. Please put in another PR.
> 
> > BTW, no offense, but does it works for you without these modifications?
> 
> Yes. I use it all the time.


That's weird...

**Pull request merged**
