### PR TITLE
Final changes for initial version of loclas

### PR DESCRIPTION
**Pull request by 813gan**
Show all values bu default and allow bulk show/hide

use list of variables as dumb id of function/frame. it's easy to implement and should work in most cases.

### CODE REVIEW

**Comment by 813gan** [comment]
It's  just minor changes. I have nothing to add.

> I'll let you merge

I'm not sure if i understand. AFAIK i cant merge anything

**Comment by rocky** [comment]
I just checked. You were sent and invite to allow you to do so. You haven't accepted though.

**Comment by 813gan** [comment]
@rocky really? I haven't seen any notification...

**Comment by rocky** [comment]
https://github.com/realgud/realgud/invitations

**Comment by 813gan** [comment]
@rocky No idea why i missed it. Now it says that invitation timed out

**Comment by rocky** [comment]
Invited again.

**Comment by 813gan** [comment]
@rocky OK. i'm in. Thanks!

**Pull request merged**
