### PR TITLE
I think this adds python flake and undoes the mess

### PR DESCRIPTION
**Pull request by rocky**
@cpitclaudel  please review. 

I think this reverts the problem I had with the some of the realgud/realgud files (specifically Makefile.am) winding parent up in realgud. 

It should also add flake8 error and warning parsing.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Dorry for the delay.  I squashed this commit the previous one and force pushed, so there should be no trace left of the mixup.  Can you check that things look right? It could be that I reverted too much in Makefile.am. And it could be that you'll need a fresh clone, due to the force-push.

**Comment by rocky** [comment]
Ok. Thanks. I did a pull from the master branch thinking it was this branch and added more changes. Let's merge this and see what remains.

**Comment by cpitclaudel** [comment]
I don't understand :/ The point of doing a force push was to erase the mix up from the history entirely, but your merge reintroduced it, right? https://github.com/realgud/realgud/commit/19d12d1798f7406b71226b1b352fd3149e1d1b1f has 60 changed files again.

**Comment by rocky** [comment]
Sigh. Again, my mistake because I pulled master instead of this branch accidentally.

Would you just fix this on master? f you want to do as a branch and merge because that's cleaner, great. At this point I don't trust myself to do.

**Comment by cpitclaudel** [comment]
Ok, I force-pushed again.  Please make a clean clone of the repo; otherwise git will ask you to merge.

**Comment by rocky** [comment]
Thanks for fixing (again). Have now cloned from scratch.

**Comment by cpitclaudel** [comment]
Thanks! Please double-check that I didn't break your change :)

**Comment by rocky** [comment]
tested now. It works great. Thanks.

**Pull request merged**
